version: 2

builds:
  - id: saga
    main: .
    binary: saga
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

  - id: saga-courier-local-file
    dir: couriers/saga-courier-local-file
    binary: saga-courier-local-file
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

  - id: saga-courier-local-stdout
    dir: couriers/saga-courier-local-stdout
    binary: saga-courier-local-stdout
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

  - id: saga-courier-slack-legacy
    dir: couriers/saga-courier-slack-legacy
    binary: saga-courier-slack-legacy
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

  - id: saga-courier-basecamp-messageboard
    dir: couriers/saga-courier-basecamp-messageboard
    binary: saga-courier-basecamp-messageboard
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: >-
      saga_{{ .Version }}_{{ .Os }}_{{ .Arch }}

checksum:
  name_template: checksums.txt

release:
  header: |-
    {{ .TagContents }}

changelog:
  sort: asc
  use: git
  abbrev: -1
  format: "{{ .ShortCommit }} {{ .Message }} ({{ .AuthorName }})"
  filters:
    exclude:
      - "^Merge "
